USE [master]
GO
/****** Object:  Database [Vegetables_Fruits]    Script Date: 12.10.2023 11:03:53 ******/
CREATE DATABASE [Vegetables_Fruits]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Vegetables_Fruits', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Vegetables_Fruits.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Vegetables_Fruits_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Vegetables_Fruits_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Vegetables_Fruits] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Vegetables_Fruits].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Vegetables_Fruits] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET ARITHABORT OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Vegetables_Fruits] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Vegetables_Fruits] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Vegetables_Fruits] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Vegetables_Fruits] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Vegetables_Fruits] SET  MULTI_USER 
GO
ALTER DATABASE [Vegetables_Fruits] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Vegetables_Fruits] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Vegetables_Fruits] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Vegetables_Fruits] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Vegetables_Fruits] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Vegetables_Fruits] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Vegetables_Fruits] SET QUERY_STORE = ON
GO
ALTER DATABASE [Vegetables_Fruits] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Vegetables_Fruits]
GO
/****** Object:  Table [dbo].[Veg_Fru_t]    Script Date: 12.10.2023 11:03:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Veg_Fru_t](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name_f] [nvarchar](30) NOT NULL,
	[Type_f] [nvarchar](30) NOT NULL,
	[Color_f] [nvarchar](20) NOT NULL,
	[Сalories_f] [int] NOT NULL,
 CONSTRAINT [PK_Veg_Fru_t] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Vegetables_Fruits] SET  READ_WRITE 
GO
